---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.7-alpine
  commands:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - python setup.py sdist bdist_wheel
  - python setup.py version
- name: dockerise
  image: plugins/docker
  settings:
    repo: saltpy/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: acceptance
  image: python:3.7-alpine
  commands:
  - pip install -r requirements.dev.txt
  - behave
  services:
  - name: selenium
    image: selenium/standalone-chrome:3.141.59
  - name: target
    image: saltpy/drone
