---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: python:3.7-alpine
  commands:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - python setup.py sdist bdist_wheel
  - python setup.py version
- name: dockerise
  image: plugins/docker
  settings:
    repo: saltpy/drone
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
image_pull_secrets:
    - dockerconfigjson
